=== nicolasevano/m2engineeringsoftware/DOC/TP1/trunk/meteo31.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<!--  xsd:schema targetNamespace="http://www.tm-xml-wiki.org/w/images/f/f2"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:cpy="http://www.tm-xml-wiki.org/w/images/f/f2"
            xmlns:station="H:\windows\workspace\DOC_TP1"
            version="1.0"
            id="ISOCountryCodeType-V2006.xsd"
            elementFormDefault="qualified"
			attributeFormDefault="unqualified" 
  		    -->

<!--  xsd:schema targetNamespace="H:\windows\workspace\DOC_TP1"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:cpy="http://www.tm-xml-wiki.org/w/images/f/f2"
            xmlns:station="H:\windows\workspace\DOC_TP1"
            version="1.0"
            id="ISOCountryCodeType-V2006.xsd"
            elementFormDefault="qualified"
			attributeFormDefault="unqualified" 
  		    -->
  		    
<xsd:schema targetNamespace=".\DOC_TP1"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:cpy="http://www.tm-xml-wiki.org/w/images/f/f2"
            xmlns:station=".\DOC_TP1"
            version="1.0"
            id="ISOCountryCodeType-V2006.xsd"
            elementFormDefault="qualified"
			attributeFormDefault="unqualified" 
  		    >  		  
  		    
<!-- sequel d'import échoué -->  		             
<!-- xsd:import namespace="http://www.tm-xml-wiki.org/w/images/f/f2" schemaLocation="ISOCountryCodeType-V2006.xsd" /-->
<!-- xsd:import namespace="file:///C:/Users/nicolas/workspace/DOC_TP1/" schemaLocation="ISOCountryCodeType-V2006.xsd" /-->

	<!-- root element -->
	 <xsd:element name="listStationMeteo" type="station:ListStationMeteo"/>
	
	<xsd:complexType name="ListStationMeteo" mixed="false">
		<xsd:sequence>
			<xsd:element ref="station:METEO" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="METEO">
        <xsd:complexType mixed="false">
				<xsd:sequence>
					<xsd:element name="metar" type="station:codemetar"/>
					<xsd:element name="paysref" type="station:pays" />
					<xsd:element name="addressref" cpy:type="adresse" minOccurs="0" maxOccurs="1" />
					<xsd:element name="nom" type="xsd:string" />
					<xsd:element name="realLatitude" type="station:latitude" />
					<xsd:element name="realLongitude" type="station:longitude" />
					<xsd:element name="altitude" type="station:Altitude" />
				</xsd:sequence>
		</xsd:complexType>
    </xsd:element>

	<xsd:simpleType name="Altitude">
		<xsd:restriction base="xsd:integer">
		</xsd:restriction>
	</xsd:simpleType>	
	
	<xsd:simpleType name="pays" cpy:type="ISOCountryCodeType" >
		<xsd:restriction base="xsd:string">
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="latitude">
		<xsd:sequence>
			<xsd:element name="realPosition" type="station:positionAbsice" />
			<xsd:element name="realAbsice" type="station:absice" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="positionAbsice">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="90" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="absice">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="nord" />
			<xsd:enumeration value="sud" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="codemetar">
		<xsd:restriction base="xsd:ID">
			<xsd:length value="4" />
			<xsd:pattern value="[A-Z]{4}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="longitude">
		<xsd:sequence>
			<xsd:element name="realPosition" type="station:positionOrdonnée" />
			<xsd:element name="realOrdonnée" type="station:ordonnée" />
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- define addresse type -->
	<xsd:complexType name="adresse" >
		<xsd:sequence>
			<xsd:element name="no" type="xsd:integer" minOccurs="1" maxOccurs="1" />
			<xsd:element name="rue" type="xsd:string" minOccurs="1" maxOccurs="2" />
			<xsd:element name="ville" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<xsd:element name="codepostal" type="xsd:string" minOccurs="1" maxOccurs="1" />
			<!-- TODO apply facettes restriction to téléphone -->
			<xsd:element name="téléphone" type="xsd:string" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="ordonnée">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ouest" />
			<xsd:enumeration value="est" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="positionOrdonnée">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="180" />
		</xsd:restriction>
	</xsd:simpleType>
	
	
	
</xsd:schema>

=== nicolasevano/m2engineeringsoftware/DOC/TP1/trunk/meteo31.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- listStationMeteo xmlns:xsd="http://www.w3.org/2001/XMLSchema" schemaLocation="meteo31.xsd"-->
<station:listStationMeteo xmlns:station=".\DOC_TP1" 
				  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				  xsi:schemaLocation=".\DOC_TP1 meteo31.xsd">
	<station:METEO>
		<!--  xsd:element name="metar" type="codemetar"/-->
		<!--  xsd:element name="paysref" type="pays" /-->
		<!--  xsd:element name="addressref" cpy:type="adresse" minOccurs="0" maxOccurs="1" /-->
		<!--  xsd:element name="nom" type="xsd:string" /-->
		<!--  xsd:element name="realLatitude" cpy:type="latitude" /-->
		<!--  xsd:element name="realLongitude" cpy:type="longitude" /-->
		<!--  xsd:element name="altidute" type="xsd:string" /-->
		<station:metar>
			LFLG
		</station:metar>
		<station:paysref>
			FR
		</station:paysref>
		<station:addressref>
			<!--  xsd:element name="no" type="xsd:integer" minOccurs="1" maxOccurs="1" /-->
			<!--  xsd:element name="rue" type="xsd:string" minOccurs="1" maxOccurs="2" /-->
			<!--  xsd:element name="ville" type="xsd:string" minOccurs="1" maxOccurs="1" /-->
			<!-- TODO apply facettes restriction to codepostal -->
			<!--  xsd:element name="codepostal" type="xsd:string" minOccurs="1" maxOccurs="1" /-->
			<!-- TODO apply facettes restriction to téléphone -->
			<!--  xsd:element name="téléphone" type="xsd:string" minOccurs="0" maxOccurs="1" /-->
			<station:no>
			5
			</station:no>
			<station:rue>
				pegaze
			</station:rue>
			<station:ville>
				Lannion
			</station:ville>
			<station:codepostal>
				22300
			</station:codepostal>
			<station:téléphone>
				0296643200
			</station:téléphone>
		</station:addressref>
		<station:nom>
				cnet
		</station:nom>
		<station:realLatitude>
		<!-- xsd:element name="realPosition" type="positionAbsice" /-->
		<!-- xsd:element name="realAbsice" type="absice" /-->
			<station:realPosition>
			<!-- hopefully... -->
				90
			</station:realPosition>
			<station:realAbsice>sud</station:realAbsice>
		</station:realLatitude>
		<station:realLongitude>
		<!--  xsd:element name="realPosition" type="positionOrdonnée" /-->
		<!--  xsd:element name="realOrdonnée" type="ordonnée" /-->
			<station:realPosition>
			<!-- hopefully... -->
				120
			</station:realPosition>
			<station:realOrdonnée>ouest</station:realOrdonnée>
		</station:realLongitude>
		<station:altitude>40</station:altitude>
	</station:METEO>
	<station:METEO>
		<!--  xsd:element name="metar" type="codemetar"/-->
		<!--  xsd:element name="paysref" type="pays" /-->
		<!--  xsd:element name="addressref" cpy:type="adresse" minOccurs="0" maxOccurs="1" /-->
		<!--  xsd:element name="nom" type="xsd:string" /-->
		<!--  xsd:element name="realLatitude" type="latitude" /-->
		<!--  xsd:element name="realLongitude" type="longitude" /-->
		<!--  xsd:element name="altidute" type="xsd:string" /-->
		<station:metar>
			LFRG
		</station:metar>
		<station:paysref>
			FR
		</station:paysref>
		<station:addressref>
			<!--  xsd:element name="no" type="xsd:integer" minOccurs="1" maxOccurs="1" /-->
			<!--  xsd:element name="rue" type="xsd:string" minOccurs="1" maxOccurs="2" /-->
			<!--  xsd:element name="ville" type="xsd:string" minOccurs="1" maxOccurs="1" /-->
			<!-- TODO apply facettes restriction to codepostal -->
			<!--  xsd:element name="codepostal" type="xsd:string" minOccurs="1" maxOccurs="1" /-->
			<!-- TODO apply facettes restriction to téléphone -->
			<!--  xsd:element name="téléphone" type="xsd:string" minOccurs="0" maxOccurs="1" /-->
			<station:no>
			5
			</station:no>
			<station:rue>
				de la coquille
			</station:rue>
			<station:ville>
				St Jacques
			</station:ville>
			<station:codepostal>
				35100
			</station:codepostal>
			<station:téléphone>
				0297643200
			</station:téléphone>
		</station:addressref>
		<station:nom>
				la noie
		</station:nom>
		<station:realLatitude>
		<!-- xsd:element name="realPosition" type="positionAbsice" /-->
		<!-- xsd:element name="realAbsice" type="absice" /-->
			<station:realPosition>
				<!-- hopefully... -->
				80
			</station:realPosition>
			<station:realAbsice>nord</station:realAbsice>
		</station:realLatitude>
		<station:realLongitude>
			<!--  xsd:element name="realPosition" type="positionOrdonnée" /-->
			<!--  xsd:element name="realOrdonnée" type="ordonnée" /-->
			<station:realPosition>
				<!-- hopefully... -->
				110
			</station:realPosition>
			<station:realOrdonnée>ouest</station:realOrdonnée>
		</station:realLongitude>
		<station:altitude>40</station:altitude>
	</station:METEO>
</station:listStationMeteo>
