=== nicolasevano/m2engineeringsoftware/DOC/TP1/trunk/meteo32.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xsd:schema		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
				targetNamespace=".\DOC_TP1"
				xmlns:releve=".\DOC_TP1"
            	elementFormDefault="qualified"
				attributeFormDefault="unqualified" 
  		    >
  	
  	<!-- root element -->
  	<xsd:element name="relevéJournalier" type="releve:RelevéJournalier"/>
  	
	<xsd:complexType name="RelevéJournalier" mixed="false">
		<xsd:sequence>
			<xsd:element name="relevéSimple" type="releve:RelevéSimple"
				minOccurs="1" maxOccurs="24" />
			<xsd:element name="cumulPrécipitation" type="releve:Précipitation" />
			<xsd:element name="jour" type="xsd:date" />
		</xsd:sequence>
	</xsd:complexType>
  	
  	<xsd:complexType name="RelevéSimple" mixed="false">
  		<xsd:sequence >
  			<xsd:element  name="relevéMetéo" type="releve:RelevéMetéo" />
  		</xsd:sequence >
  	</xsd:complexType>
  	
  	<xsd:simpleType name="Temperature" >
		<xsd:restriction base="xsd:string" >
			<xsd:pattern value="[0-9]+°[F|C]" />
		</xsd:restriction>
	</xsd:simpleType >
	
	<xsd:complexType name="RelevéMetéo" mixed="false">
			<xsd:sequence >
				<xsd:element name="dateRelevé" type="xsd:date" />
				<xsd:element name="heurRelevé" type="releve:dtime" />
				<xsd:element name="pression" type="releve:dpression" />
				<xsd:element name="humidité" type="releve:percent"/>
				<xsd:element name="vent" type="releve:Vent" />
			</xsd:sequence >
			<xsd:attribute name="dtemperature" type="releve:Temperature" use="required"/>
	</xsd:complexType>
	
	<xsd:simpleType name="dtime">
		<xsd:restriction base="xsd:time">
			<!-- xsd:pattern value="hh:mm:ss+?-?hh:mm]" /-->
			<xsd:pattern value="[0-9]{2}\:[0-9]{2}\:[0-9]{2}[+|-][0-9]{2}\:[0-9]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="dpression">
		<xsd:restriction base="xsd:integer">
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="percent">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="100|[0-9]{2}|[0-9]{1}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="Vent" mixed="false">
			<xsd:sequence  >
				<xsd:element name="force" type="releve:forceVent" />
				<xsd:element name="direction" type="releve:PointCardinaux" />
			</xsd:sequence >
	</xsd:complexType>
	
	<xsd:simpleType name="forceVent">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+ [ms|m/s|km/s|m/h]+|1[0-2]{1}|[0-9]{1}" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="PointCardinaux">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="N|NE|NO|S|SE|SO|E|O" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="Précipitation">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]+ mm" />
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== nicolasevano/m2engineeringsoftware/DOC/TP1/trunk/meteo32.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve:relevéJournalier xmlns:releve=".\DOC_TP1" 
						 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
						 xsi:schemaLocation=".\DOC_TP1 meteo32.xsd ">
  <!--Auto generate and updated with eclipse and plug in Rinzo xml editor 
  free work better and cost less-->						 
  <releve:relevéSimple>
  	<!-- releve:relevéMetéo dtemperature="12 °C"-->
  	<!-- releve:relevéMetéo dtemperature="12 °T"-->
    <releve:relevéMetéo dtemperature="12°C">
      <releve:dateRelevé>2001-01-01</releve:dateRelevé>
      <releve:heurRelevé>12:00:00+00:00</releve:heurRelevé>
      <!-- releve:heurRelevé>12:00:00+00:00</releve:heurRelevé-->
      <releve:pression>0</releve:pression>
      <!--  releve:humidité>1000</releve:humidité-->
      <!--  releve:humidité>-3</releve:humidité-->
      <releve:humidité>50</releve:humidité>
      <releve:vent>
        <!--<releve:force>13tkm/s</releve:force>  -->
        <!-- releve:force>13</releve:force -->
        <releve:force>11</releve:force>
        <!-- releve:direction>EN</releve:direction -->
        <releve:direction>NE</releve:direction>
      </releve:vent>
    </releve:relevéMetéo>
  </releve:relevéSimple>
  <releve:relevéSimple>
    <releve:relevéMetéo dtemperature="21°C">
      <releve:dateRelevé>2001-01-01</releve:dateRelevé>
      <releve:heurRelevé>18:00:00+00:00</releve:heurRelevé>
      <releve:pression>0</releve:pression>
      <releve:humidité>50</releve:humidité>
      <releve:vent>
        <releve:force>50 km/s</releve:force>
        <releve:direction>NE</releve:direction>
      </releve:vent>
    </releve:relevéMetéo>
  </releve:relevéSimple>
  <releve:relevéSimple>
    <releve:relevéMetéo dtemperature="19°C">
      <releve:dateRelevé>2001-01-01</releve:dateRelevé>
      <releve:heurRelevé>20:00:00+00:00</releve:heurRelevé>
      <releve:pression>0</releve:pression>
      <releve:humidité>100</releve:humidité>
      <releve:vent>
        <releve:force>11</releve:force>
        <releve:direction>NE</releve:direction>
      </releve:vent>
    </releve:relevéMetéo>
  </releve:relevéSimple>
  <releve:cumulPrécipitation>10 mm</releve:cumulPrécipitation>
  <releve:jour>2001-01-01</releve:jour>
</releve:relevéJournalier>
