=== nicolasevano/m2engineeringsoftware/DOC/TP3/trunk/cuisine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="description" type="xs:string"/>
	<xs:element name="ingredient">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ingredient" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="preparation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="nom" type="xs:string" use="required"/>
			<xs:attribute name="qte" type="quantité"/>
			<xs:attribute name="unit">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="can"/>
						<xs:enumeration value="cup"/>
						<xs:enumeration value="jar"/>
						<xs:enumeration value="ounce"/>
						<xs:enumeration value="package"/>
						<xs:enumeration value="pound"/>
						<xs:enumeration value="ribs"/>
						<xs:enumeration value="tablespoon"/>
						<xs:enumeration value="teaspoon"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="nom" type="xs:string"/>
	<xs:element name="note" type="xs:string"/>
	<xs:element name="nutrition">
		<xs:complexType>
			<xs:attribute name="calories" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">

					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="gras" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="glucides" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
					
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="proteines" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="alcool" type="xs:byte"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pas" type="xs:string"/>
	<xs:element name="preparation">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pas" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="recette">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nom"/>
				<xs:element ref="ingredient" maxOccurs="unbounded"/>
				<xs:element ref="preparation"/>
				<xs:element ref="note" minOccurs="0"/>
				<xs:element ref="nutrition"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="recettes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description"/>
				<xs:element ref="recette" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:simpleType name="quantité">
		<xs:restriction base="xs:string">	
			<xs:pattern value="[0-9]+|[0-9]+\.[0-9]+|\.[0-9]+|\*"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== nicolasevano/m2engineeringsoftware/DOC/TP3/trunk/cuisine.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="recette2nutrition.xslt"?>
<recettes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="H:\windows\workspace\DOC_XSLT\cuisine.xsd">
	<description>
     Quelques exemples de recettes (en anglais)
  </description>
	<recette>
		<nom>Beef Parmesan with Garlic Angel Hair Pasta</nom>
		<ingredient nom="beef cube steak" qte="1.5" unit="pound"/>
		<ingredient nom="onion, sliced into thin rings" qte="1"/>
		<ingredient nom="green bell pepper, sliced in rings" qte="1"/>
		<ingredient nom="Italian seasoned bread crumbs" qte="1" unit="cup"/>
		<ingredient nom="grated Parmesan cheese" qte="0.5" unit="cup"/>
		<ingredient nom="olive oil" qte="2" unit="tablespoon"/>
		<ingredient nom="spaghetti sauce" qte="1" unit="jar"/>
		<ingredient nom="shredded mozzarella cheese" qte="0.5" unit="cup"/>
		<ingredient nom="angel hair pasta" qte="12" unit="ounce"/>
		<ingredient nom="minced garlic" qte="2" unit="teaspoon"/>
		<ingredient nom="butter" qte="0.25" unit="cup"/>
		<preparation>
			<pas>
        Preheat oven to 350 degrees F (175 degrees C).
      </pas>
			<pas>
        Cut cube steak into serving size pieces. Coat meat with the bread crumbs
        and parmesan cheese. Heat olive oil in a large frying pan, and saute 1
        teaspoon of the garlic for 3 minutes. Quick fry (brown quickly on both sides)
        meat. Place meat in a casserole baking dish, slightly overlapping edges.
        Place onion rings and peppers on top of meat, and pour marinara sauce
        over all.
      </pas>
			<pas>
        Bake at 350 degrees F (175 degrees C) for 30 to 45 minutes, depending on
        the thickness of the meat. Sprinkle mozzarella over meat and leave in the
        oven till bubbly.
      </pas>
			<pas>
        Boil pasta al dente. Drain, and toss in butter and 1 teaspoon garlic. For a
        stronger garlic taste, season with garlic powder. Top with grated parmesan
        and parsley for color. Serve meat and sauce atop a mound of pasta!
      </pas>
		</preparation>
		<note>
      Make the meat ahead of time, and refrigerate over night, the acid in the
      tomato sauce will tenderize the meat even more. If you do this, save the
      mozzarella till the last minute.
    </note>
		<nutrition calories="1167" gras="23" glucides="45" proteines="32"/>
	</recette>
	<recette>
		<nom>Ricotta Pie</nom>
		<ingredient nom="filling">
			<ingredient nom="ricotta cheese" qte="3" unit="pound"/>
			<ingredient nom="eggs" qte="12"/>
			<ingredient nom="white sugar" qte="2" unit="cup"/>
			<ingredient nom="vanilla extract" qte="2" unit="teaspoon"/>
			<ingredient nom="semisweet chocolate chips" qte="0.25" unit="cup"/>
			<preparation>
				<pas>
          Beat the 12 eggs, 2 cups sugar and vanilla extract together. Stir in
          the ricotta cheese and the chocolate chips. Set aside.
        </pas>
			</preparation>
		</ingredient>
		<ingredient nom="dough">
			<ingredient nom="flour" qte="4" unit="cup"/>
			<ingredient nom="baking powder" qte="5" unit="teaspoon"/>
			<ingredient nom="white sugar" qte="1" unit="cup"/>
			<ingredient nom="shortening" qte="0.5" unit="cup"/>
			<ingredient nom="eggs, lightly beaten" qte="4"/>
			<ingredient nom="vanilla extract" qte="1" unit="teaspoon"/>
			<preparation>
				<pas>
          Combine the flour, baking powder, and 1 cup of the sugar together. Cut in the
          shortening and mix until the mixture resembles coarse crumbs. Mix in 4 of
          the eggs and 1 teaspoon of the vanilla. Divide dough into 4 balls and chill (if
          needed).
        </pas>
			</preparation>
		</ingredient>
		<ingredient nom="milk" qte="*"/>
		<preparation>
			<pas>
        Preheat oven to 325 degrees F (165 degrees C). Grease two deep dish pie
        plates.
      </pas>
			<pas>
        Roll out 2 of the balls to fit into the pie pans. Do not make the crust too thick
        as it will expand during cooking and get too thick. Do not flute the edges of
        the dough. Roll out the other 2 balls of dough and cut each into 8 narrow
        strips for the top of the crust. Alternately you can use cookie cutters and
        place the cutouts on the top of the pies.
      </pas>
			<pas>
        Pour the filling evenly into the pie crusts. Top each pie with 8 narrow strips
        of dough or cookie cut-outs. Brush top of pie with milk for shine. Place foil on
        the edge of crust.
      </pas>
			<pas>
        Bake at 325 degrees F (165 degrees C) for 20 to 30 minutes then remove
        foil. Continue to bake for another 25 or 30 minutes or until a knife inserted in
        the center comes out clean.
      </pas>
		</preparation>
		<nutrition calories="349" gras="18" glucides="64" proteines="18"/>
	</recette>
	<recette>
		<nom>Linguine Pescadoro</nom>
		<ingredient nom="linguini pasta" qte="16" unit="ounce"/>
		<ingredient nom="sauce">
			<ingredient nom="olive oil" qte="2" unit="tablespoon"/>
			<ingredient nom="minced cloves of garlic" qte="2"/>
			<ingredient nom="Italian seasoning" qte="0.5" unit="teaspoon"/>
			<ingredient nom="dried thyme" qte="0.25" unit="teaspoon"/>
			<ingredient nom="crushed red pepper flakes" qte="0.25" unit="teaspoon"/>
			<ingredient nom="crushed tomatoes" qte="1" unit="can"/>
			<ingredient nom="black olives, drained" qte="6" unit="ounce"/>
			<ingredient nom="whole baby clams" qte="10" unit="ounce"/>
			<ingredient nom="minced clams, with juice" qte="6.5" unit="ounce"/>
			<ingredient nom="small salad shrimp" qte="0.25" unit="pound"/>
			<ingredient nom="scallops" qte="0.25" unit="pound"/>
			<ingredient nom="lemon zest" qte="2.5" unit="teaspoon"/>
			<ingredient nom="salt" qte="*"/>
			<ingredient nom="ground black pepper" qte="*"/>
			<preparation>
				<pas>
          In a heavy saucepan over medium heat saute garlic in olive oil
          until garlic softens.
        </pas>
				<pas>
          Add Italian seasoning, thyme, crushed red pepper flakes,
          crushed tomatoes, black olives, and the juice from both cans of clams.
          Simmer for 15 minutes.
        </pas>
				<pas>
          Mix in canned clams, shrimp, scallops, lemon zest,
          and salt and pepper to taste.
        </pas>
				<pas>
          Simmer for an additional 15 minutes or until
          shrimp and clams are cooked.
        </pas>
			</preparation>
		</ingredient>
		<preparation>
			<pas>
        In a large pot of boiling salted water cook linguini until al dente. Drain.
      </pas>
			<pas>
        Toss cooked and drained linguine pasta over seafood sauce. Serve warm.
      </pas>
		</preparation>
		<nutrition calories="532" gras="12" glucides="59" proteines="29"/>
	</recette>
	<recette>
		<nom>Zuppa Inglese</nom>
		<ingredient nom="egg yolks" qte="4"/>
		<ingredient nom="milk" qte="2.5" unit="cup"/>
		<ingredient nom="Savoiardi biscuits" qte="21"/>
		<ingredient nom="sugar" qte="0.75" unit="cup"/>
		<ingredient nom="Alchermes liquor" qte="1" unit="cup"/>
		<ingredient nom="lemon zest" qte="*"/>
		<ingredient nom="flour" qte="0.5" unit="cup"/>
		<ingredient nom="fresh whipping cream" qte="*"/>
		<preparation>
			<pas>
        Warm up the milk in a nonstick sauce pan
      </pas>
			<pas>
        In a large bowl beat the egg yolks with the sugar, add the flour 
        and combine the ingredients until well mixed.
      </pas>
			<pas>
        Add the milk, a little bit at the time to the egg mixture, mixing well.
      </pas>
			<pas>
        Put the mixture into the sauce pan and cook it on the stove at a medium 
        low heat. Mix the cream continuously with a wooden spoon. When it starts
        to thicken remove it from the heat and pour it on a large plate to cool off.
      </pas>
			<pas>
        Stir the cream now and then so that the top doesn't harden.
      </pas>
			<pas>
        Dip quickly both sides of the lady fingers in the liquor. Layer them one 
        at the time in a glass bowl large enough to contain 7 biscuits.
      </pas>
			<pas>
        Spread 1/3 of the cream and repeat the layer with lady fingers. Finish 
        with the cream.
      </pas>
		</preparation>
		<note>
      Refrigerate for at least 4 hours better yet overnight. Before serving 
      decorate the zuppa inglese with whipped cream.
    </note>
		<nutrition calories="612" gras="49" glucides="45" proteines="4" alcool="2"/>
	</recette>
	<recette>
		<nom>Cailles en Sarcophages</nom>
		<ingredient nom="pastry">
			<ingredient nom="chilled unsalted butter" qte="15" unit="ounce"/>
			<ingredient nom="flour" qte="3" unit="cup"/>
			<ingredient nom="salt" qte="1.5" unit="teaspoon"/>
			<ingredient nom="ice water" qte="0.75" unit="cup"/>
			<preparation>
				<pas>
          In a large bowl, cut 6 tablespoons of the butter into the flour with 
          a pastry blender until the butter is more or less incorporated. Now 
          coarsely cut the remaining butter into the flour mixture, leaving many 
          visible pieces of butter (about 1/4 inch in diameter should be fine).
        </pas>
				<pas>
          Dissolve the salt into the ice water. Slowly drizzle the salted water 
          into the flour mixture while tossing gently with a fork. When all the water
          has been evenly distributed, there will remain many dry crumbs. Don't worry.
        </pas>
				<pas>
          Empty the dough out onto a large piece of plastic wrap. By folding up the 
          four sides of the wrap and pressing, form a rectangle of dough. Roll the
          dough out just a bit and fold the sides over the middle, forming a piece 
          one third the former size. Repeat, this time folding the top and bottom
          to the middle. The butter and flour will not yet be working in harmony, so 
          you will probably have to use the plastic wrap to aid you in the first
          few folds.
        </pas>
				<pas>
